version: '3.8'

services:
  # 1. BANCO DE DADOS 
  database:
    image: postgres:15-alpine
    container_name: biblioteca-db
    restart: always
    env_file:
      - .ENV 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - biblioteca-network

  # 2. BACKEND 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biblioteca-backend
    restart: always
    env_file:
      - .ENV 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - database
    networks:
      - biblioteca-network

  # 3. FRONTEND 
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: biblioteca-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - biblioteca-network

networks:
  biblioteca-network:
    driver: bridge

volumes:
  postgres_data: